# Generated by Django 5.0.6 on 2024-12-21 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='office',
            name='location',
        ),
        migrations.CreateModel(
            name='Office_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.location')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.office')),
            ],
        ),
    ]
