# Generated by Django 5.0.6 on 2024-12-21 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_location_is_present_remove_office_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_location',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_office_location', to='hr.location'),
        ),
        migrations.AlterField(
            model_name='office_location',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_office_location', to='hr.office'),
        ),
        migrations.AlterUniqueTogether(
            name='office_location',
            unique_together={('office', 'is_present')},
        ),
    ]
